### ISSUE TITLE
May I SetMinUpdatePeriod bigger than KEEP_ALIVE value?

### ISSUE THREAD

**Issue by bhui** [Countly/countly-sdk-cpp#4]
A session sync request per 30s(KEEP_ALIVE) maybe took huge pressure to our server.
So we'd like to change parameter like this, would this be ok?
```
SetMaxEventsPerMessage(100);  //100 is too big?
SetMinUpdatePeriod(15 * 60 * 1000); //period too long?
```

**Comment by LVMBDV** [comment]
I've looked at the implementation and there is a problem with using really large numbers for `SetMaxEventsPerMessage`, the implementation uses a GET request to make the API call which sends the event data in the URL. This may cause the reverse-proxy in front of the API server or the API server itself to reject the request because its target path is too large. The actual limits of this vary widely due to it being an arbitrary configuration, not set in the RFC :smile:. I'll modify `CountlyConnectionQueue::UpdateSession` to use POST requests instead, to prevent this.

The optimal values for these parameters depend on how frequent your application generates events, whether latency or bandwidth are bottlenecks for your Countly server and a few parameters in your Countly server configuration as well. Be sure to modify "Session cooldown" and "Maximal Session Duration" under Configurations > Api in your Countly instance accordingly with the update period and keepalive intervals to prevent session fragmentation.

**Comment by ar2rsawseen** [comment]
@LVMBDV just FYI from SDK development guide about using POST or GET:
https://resources.count.ly/docs/sdk-development-guide#section-using-get-or-post

**Comment by LVMBDV** [comment]
The rewrite implements GET/POST switching, closing this.
